[project]
name = "lab-tic-tac-toe-step-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.1.1",
    "redis>=6.2.0",
]
